### ISSUE TITLE
ArgumentException using in a different project

### ISSUE THREAD

**Issue by BrennonTWilliams** [keijiro/Smrvfx#10]
I'm trying to use Smrvfx in a new project. I exported the assets as a unitypackage, and when I open the Karate scene I get the error:

ArgumentException: Attempting to create a zero length compute buffer
Parameter name: count
UnityEngine.ComputeBuffer..ctor (System.Int32 count, System.Int32 stride, UnityEngine.ComputeBufferType type, UnityEngine.ComputeBufferMode usage, System.Int32 stackDepth) (at C:/buildslave/unity/build/Runtime/Export/Shaders/ComputeShader.bindings.cs:82)
UnityEngine.ComputeBuffer..ctor (System.Int32 count, System.Int32 stride) (at C:/buildslave/unity/build/Runtime/Export/Shaders/ComputeShader.bindings.cs:65)
Smrvfx.SkinnedMeshBaker.TransferData () (at Assets/Smrvfx/SkinnedMeshBaker.cs:127)
Smrvfx.SkinnedMeshBaker.Update () (at Assets/Smrvfx/SkinnedMeshBaker.cs:77)

How do I correctly import Smrvfx to use in another project?
Thanks!

**Comment by keijiro** [comment]
Did you correctly export motion/model files in the `Packages` directory? These files are imported via Package Manager, so they're not in the `Assets` directory.

**Comment by BrennonTWilliams** [comment]
Yes, I tried re-importing the packages folder and got an error saying I already had them. But in the Karate scene the Beta Optimized prefab was missing. I re-exported the smrvfx packages and I got a message saying they are already there. However I looked at the manifest file in your project and added what was missing in my manifest.

In lock:
"jp.keijiro.beta": {
      "hash": "01208e373fccf53416e68dfc1afb775d0c3219f4",
      "revision": "HEAD"
    },
    "jp.keijiro.cmu-mocap": {
      "hash": "8fda0c1770156a047ed44868c5132748960b01cf",
      "revision": "upm"

In dependencies:

"jp.keijiro.beta": "https://github.com/keijiro/jp.keijiro.beta.git",
    "jp.keijiro.cmu-mocap": "https://github.com/keijiro/CMUMocap.git#upm"

Otherwise our manifest files look the same, though I'm on 2019.2.5f1. Unfortunately the project already has a lot of work put into it so I can't downgrade.

After updating the manifest files I got 46 errors, most of which look like this:

Required property 'name' not set (Packages/com.unity.timeline/Editor/Unity.Timeline.Editor.asmdef)



Is there a better way to pull your project into mine?

Also, I just wanted to say thank you for making such amazing work public. Your projects are truly inspirational and just incredible to learn from. I really really hope I can get this incredible project working in mine!

**Comment by keijiro** [comment]
I don't recommend using these test models/animations. I think you can use Smrvfx without any issue when using your own models/animations.

**Comment by BrennonTWilliams** [comment]
I'm using it on my own character now, as you instructed. In my scene I have:
- The character, which has an animator, skinned mesh renderer, bones, etc
- Baker, source set to the character's skinned mesh renderer. All the maps are set to the same objects in the demo scene since that's all I have.
- Particles, Visual Effect component's asset set to the Particles object included
- Timeline, with the playable director component
- Volume. There is a problem here, I cannot attach the volume.cs script. In the Karate scene there's an error: "The associated script cannot be loaded. Please fix any compile errors and assign a valid script." Looking at the script I do not see what the issue is. Will the whole system break completely without volume.cs?

I'm not sure which elements are critical and which are not important to get it to work. Currently the character just goes through its normal animation without any effects. Is there an easy way to get it working? Or does volume.cs need to be fixed for it to work?

Thank you so much again!

**Comment by keijiro** [comment]
Could you share a minimal project that reproduces the issue?

**Comment by BrennonTWilliams** [comment]
Sure, the project is pretty big so I'll recreate it tonight.

I'm also using SteamVR if that has an impact.

What is the best way for me to send it to you?

**Comment by keijiro** [comment]
> What is the best way for me to send it to you?

If the project is small enough, you can attach it here. Or you can create a GitHub repository to share it.

Google Drive or Dropbox or something like them are okay too.

**Comment by keijiro** [comment]
I'm closing this issue now as I assume it has been already solved. Please feel free to reopen for further questions.
