### ISSUE TITLE
Can't get the spawning correct

### ISSUE THREAD

**Issue by enginarer** [keijiro/Smrvfx#11]
When I try to create a new VFX graph, it only bursts a single line of particles, instead of covering the whole skeletal mesh and most of the time it bursts only once, even if it's set to constant spawn.

Am I missing something here?

![VFX_test](https://user-images.githubusercontent.com/17747440/67776433-5c66cc00-fa71-11e9-927a-d5e1ba7c77d2.png)

**Comment by keijiro** [comment]
Could you provide the graph that reproduces the issue?

**Comment by enginarer** [comment]
For this one on the screenshot, I basically duplicated the one (particles.vfx) in your project folder and double clicked it to edit. As soon as I'm in the VFX graph screen, even without changing any node and/or hitting "compile", it suddenly converted into this.

Without editing any of the VFX files that come in your project, it works just fine. As soon as I edit one, or try to create a new one, it ends up like in the screenshot.

I'm on the latest stable version 2019.2.10

**Comment by keijiro** [comment]
Did you set the VFX properties (position map, velocity map, etc.) correctly?

**Comment by enginarer** [comment]
Yes, I think so. I can send a screenshot of that as well in a few hours when I get back home. But even when I try to edit one of your VFX files, it still does that. So, unless Unity messes with how the properties are set up when I go into the edit screen, I think that has no effect on the issue as well :(

I'll try to recreate the issue on another computer I can find where I am now, so I can see if this is just my PC or a general thing.

**Comment by enginarer** [comment]
This is the duplicate from your Particles.vfx file. Again, it works like a charm after duplicated, but the moment I double-clicked and got to the edit screen to take a screenshot, the spawning breaks down again as well as the constant spawning.

I couldn't find another PC that I could recreate the issue, I will try to find one if I can. I'll share the results here if I do so.

![particles](https://user-images.githubusercontent.com/17747440/67871814-001fad00-fb42-11e9-8440-414691541ade.png)

**Comment by enginarer** [comment]
I still can't figure out what's wrong and come up with a solution. It somehow seems to be related with the render textures, Position one initially...

![smrvfx](https://user-images.githubusercontent.com/17747440/68548032-98971680-03f9-11ea-80fc-d0b149cd0599.png)

**Comment by keijiro** [comment]
Could you provide this project for me? Please don't hesitate to share it. When trying to solve this kind of setup issues, it's essential to share the same condition.

**Comment by enginarer** [comment]
Hi, sorry I couldn't follow up for a while. Here's exactly your project, but after me opening the VFX graphs and them becoming "defected". I hope that helps...

[Smrvfx-test.zip](https://github.com/keijiro/Smrvfx/files/3871358/Smrvfx-test.zip)

**Comment by keijiro** [comment]
Thanks for sharing it. Unfortunately, it doesn't reproduce on my side. They work correctly even after opening them in the VFX Editor.

Not completely related, but I updated the project with Unity 2019.3 (beta). I think it's worth giving a try with 2019.3 because there are several fixes/improvements in HDRP and VFX Graph.

**Comment by enginarer** [comment]
Ah ok, so this is as I feared. I have to find out what's wrong on my system in this case. Thank you so much for your support Keijiro!
