### ISSUE TITLE
Multiple Mesh Renders

### ISSUE THREAD

**Issue by xubi1993** [keijiro/Smrvfx#12]
Hello,
         Can we use this on multiple mesh renders. Like in this example:

Link: https://www.youtube.com/watch?v=Ka6IIuqQ8Dc

Can I use multiple mesh renders to achieve the same affect with multiple people with each person assigned his own mesh render to be driven by the depth camera?

**Comment by keijiro** [comment]
> Can we use this on multiple mesh renders.

Yes.

> Can I use multiple mesh renders to achieve the same affect with multiple people with each person assigned his own mesh render to be driven by the depth camera?

It sounds like possible but depends on your implementation and the specs of the device.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.

**Comment by xubi1993** [comment]
Hello Again,
                    I try to combines the meshes before passing it to the compute shader but the mesh combining does not work well and not good for performance.

Than I tried to pass the skinned meshes in form of an array but the compute shader overrides each time its called so only last passed mesh gets processed. Any idea how to combine mesh data before sending it to the shader or keep the position data in the texture until all position data is processed and than override in the next frame. Thanks.

**Comment by keijiro** [comment]
I think just using multiple instances of SkinnedMeshBaker and VFX is enough for rendering multiple meshes. It might be better than spending a significant amount of process time for combining them before baking.

**Comment by xubi1993** [comment]
Thanks @keijiro  it works like a charm :)

**Comment by albertobonanni** [comment]
Hi Keijiro, I am having the same issue but I haven't yet managed to solve it. I have three different avatars: one is rendering motion capture data (depth camera), whereas the other two have different animations applied. I am trying to apply the same VFX graph to all of them, but as mentioned the meshbaker overrides and only renders the first mesh. Do you know how can I list different meshes? I tried to instance multiple baker/vfx game objects with different meshes as sources,, but this is the result. Thank you in advance @keijiro !

![Screenshot 2020-01-27 22 59 02](https://user-images.githubusercontent.com/48488032/73221444-bfdbc500-4158-11ea-92f5-2e6da5e8c4c4.png)

**Comment by albertobonanni** [comment]
Ok it just took me a while to process what you guys have been talking about.. it actually works. Amazing!!
