### ISSUE TITLE
Git Package Support

### ISSUE THREAD

**Issue by chikashimiyama** [keijiro/Smrvfx#13]
Hi, 
I'm interested in trying out this repo.

as you instructed I added 
    "jp.keijiro.smrvfx" : "https://github.com/keijiro/Smrvfx.git"

to my menifest.json but I get the following error.

> An error occurred while resolving packages:
>   Project has invalid dependencies:
>     jp.keijiro.smrvfx: [https://github.com/keijiro/Smrvfx.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository.
> 

Is this post related to this issue?

https://answers.unity.com/questions/1582586/package-manager-using-git-repo.html

I'm using Unity 2019.2.8f on windows. Git path is set up properly.

thanks

**Comment by keijiro** [comment]
Sorry for the delay in response.

> as you instructed I added
> "jp.keijiro.smrvfx" : "https://github.com/keijiro/Smrvfx.git"

Where did you see this instruction? This example (Smrvfx) isn't tailored as an importable package, so you can't import it via the Package Manager. You can just download the entire project and open it. If you'd like to use it in your own project, you have to copy the related files manually.

**Comment by keijiro** [comment]
I'm closing this issue ticket now. Please feel free to reopen for further problems.
