### ISSUE TITLE
How to connect with kinect?

### ISSUE THREAD

**Issue by handhikadsa** [keijiro/Smrvfx#17]
Hi Mr.Keijiro, im interested with your work, can this vfx connect with kinect? and if it does, may you show me how to do it?, Thank You kind sir :)

**Comment by keijiro** [comment]
Please check the Akvfx repository: https://github.com/keijiro/Akvfx

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by handhikadsa** [comment]
Hi Mr.Keijiro Thank you for the reply, and sorry for my late reply, im sorry before, i mean how to connect the xbox one kinect v2 with this, i have seen your Akvfx repository, but its a different kinect :(. Thank You Sir

**Comment by keijiro** [comment]
There is no compatibility between Azure Kinect and Kinect V2, and I don't have any Kinect V2 device. So, unfortunately, there is no way to support it.

**Comment by handhikadsa** [comment]
i understand, thank you sir for your response :)

**Comment by handhikadsa** [comment]
> There is no compatibility between Azure Kinect and Kinect V2, and I don't have any Kinect V2 device. So, unfortunately, there is no way to support it.

i understand, thank you sir for your response :)

**Comment by sergiobd** [comment]
@handhikadsa, check this repository: https://github.com/roelkok/Kinect-VFX-Graph

**Comment by handhikadsa** [comment]
> @handhikadsa, check this repository: https://github.com/roelkok/Kinect-VFX-Graph

wow thank you so muchhh my dudeeeeeeee appreciate it

**Comment by Hiran-Nair** [comment]
> 

Will this VFX work on Kinect V2?

**Comment by Hiran-Nair** [comment]
@handhikadsa Did you get a chance to get it worked on Kinect V2? Please let me know.

**Comment by handhikadsa** [comment]
> @handhikadsa Did you get a chance to get it worked on Kinect V2? Please let me know.

sadly i dont get any chances
