### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Phantomx2** [keijiro/Smrvfx#18]
Scripts and animation files seems to be missing from the repo since last commits making the effect not working. 
I am curious to see it working with property binders instead of texture, so if you can add in the files that would be very nice!

Thanks!

**Comment by keijiro** [comment]
The issue doesn't reproduce on my side. Could you start over from a clean clone of the master branch? I'd recommend using Unity 2019.3.13f1.

**Comment by Phantomx2** [comment]
Never mind, I was missing the packages for some reason.
