### ISSUE TITLE
can't move model to other part than root of scene

### ISSUE THREAD

**Issue by mickeyvanolst** [keijiro/Smrvfx#19]
There doesn't seem to be a way to change the location of the object. 

Tried several approaches, but either the effect disappears when a camera isn't looking at the root, or (in case of only moving the effect) the model doesn't animate and stays in its default state. What would be the correct way to do this?

**Comment by mickeyvanolst** [comment]
This issue also happens with the burst wig repo.

**Comment by keijiro** [comment]
The easiest workaround is to enlarge the VFX bounds, like (10000, 10000, 10000).

**Comment by apkd** [comment]
I have created a pull request that attempts to remediate this problem:
https://github.com/keijiro/Smrvfx/pull/23

**Comment by keijiro** [comment]
I'm closing this issue as I changed the main aim of this repository to provide an example of the built-in mesh sampling feature. You can easily avoid the problem with the built-in one.
