### ISSUE TITLE
Error since the recent update

### ISSUE THREAD

**Issue by andybak** [keijiro/Smrvfx#2]
Graphics.CopyTexture can only copy between same texture format groups (d3d11 base formats: src=9 dst=1)

No traceback but the error disappears if I comment out the three CopyTexture calls in SkinnedMeshBaker

**Comment by keijiro** [comment]
Thanks for pointing it out. Yes, that change can cause an issue on DX11. I fixed it on the latest commit.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.

**Comment by andybak** [comment]
Yep. Fix worked for me. Thanks!
