### ISSUE TITLE
Possible to upsample the skinned mesh renderer ?

### ISSUE THREAD

**Issue by Levrden** [keijiro/Smrvfx#22]
Hello
Smrvfx works perfectly, but the skinned mesh i use is low poly, so all the particles come from the same points and it is quite ugly.
Like with the shuriken particle system, i would like to emit from the triangle, or to sample uniform points on the skinned mesh
Do you have an idea on how to achieve it ?

Thanks !

**Comment by keijiro** [comment]
That's a nice-to-have feature. Unfortunately, I can't make time for it.

An official implementation of a skinned mesh emitter for VFX Graph is under development. I'd recommend waiting for it to come out.

**Comment by Levrden** [comment]
Okay, it's good to know !
I don't have much time to wait for it, so i will try by myself
Thanks

**Comment by keijiro** [comment]
Added https://github.com/keijiro/Smrvfx/commit/ccb8f252ec5eb4e2fe9a269a0d63b733b23cae14
