### ISSUE TITLE
Beta Optimized がMissing Prefabとなってしまいます。

### ISSUE THREAD

**Issue by scsTakeda** [keijiro/Smrvfx#26]

**Comment by scsTakeda** [comment]
初心者的な質問で申し訳ありません。
プロジェクトを開くとBeta Optimized がMissing Prefabとなってしまいます。
モーション付きのキャラクターが必要かと思うのですが見当たらない状態です。
UNITY2020.1.13f1を使用しています。
マニュフェストはわからないながら以下の様な内容に書き換えています。

{
  "scopedRegistries": [
    {
      "name": "Keijiro",
      "url": "https://registry.npmjs.com",
      "scopes": [ "jp.keijiro" ]
    }
  ],
  "dependencies": {
    "jp.keijiro.smrvfx": "1.1.6",    "com.unity.render-pipelines.high-definition": "8.2.0",
    "com.unity.timeline": "1.4.2",
    "jp.keijiro.cmu-mocap": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by keijiro** [comment]
`manifest.json` から `jp.keijiro.beta` が削除されているためエラーが発生しています。元に戻してお試しください。
