### ISSUE TITLE
Adding the smrvfx and akvfx packages to one project?

### ISSUE THREAD

**Issue by laurienvictoria** [keijiro/Smrvfx#28]
Hi, I would love to combine the smrvfx and your akvfx in one project, but am struggling as this one is dependant on unity 2020, and the akvfx on unity 2019.

Is there a way I can put both in one project?

**Comment by keijiro** [comment]
Both of them support Unity 2020, so please use 2020.

I'm closing this issue now. Please reopen it for further problems.

**Comment by laurienash-fiftynine** [comment]
Thanks for your input!!!
I couldn't get the akvfx working by copying & pasting the scoped registries & dependencies in the how to install, but when switching out my manifest for the one in your project (which includes the Unity NuGet scoped registry) it worked fine :)

**Comment by keijiro** [comment]
You're right. Akvfx requires the NuGet registry. I'll fix the doc. Thanks.
