### ISSUE TITLE
crash project in 2019.1.7f1

### ISSUE THREAD

**Issue by artistd36** [keijiro/Smrvfx#3]
Hi,

It's crash while opening the project.

Unity - 2019.1.7f1

**Comment by keijiro** [comment]
It doesn't reproduce on my side.

- Which platform are you using?
- Could you provide the Editor log file? See below for details.

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen if it still reproduces.
