### ISSUE TITLE
Any resolution limitation?

### ISSUE THREAD

**Issue by CZHALO** [keijiro/Smrvfx#35]
Hi Keijiro,

I have a problem aboutSmrvfx, 
I'm working on a Unity Project recently, conbined with KlakSpout & Smvfx , and the Azure Kinect Example from RF solutions: https://assetstore.unity.com/packages/tools/integration/azure-kinect-examples-for-unity-149700

The project is about using Azure Kinect to detect users, when users shows up, the avatar should be controlled by skeleton and activated the vfx attached on it. 

The project is almost done, but the GPU pressure is little too much for the PC my project would be installed, since I try to keep the visual effect,  I found that lower the camera resolution helps a lot, unitil I set it lower than 1560*720, when it's lower than 1560*720, the Avatar cotrolled by Azure is moving correctly, and the Throttle Value & transform value is changing as expected by checking in Scene View, but in Game View & Build Game View, there just pure black.

I've tried plenty of build resolution, all of them didn't work when it's lower than 1560*720. I wonder: Is there any resolution limitation for this vfx to be seen?

**Comment by keijiro** [comment]
A simple answer is no. There is no such a limitation.

I think there is nothing causing the issue on my side. I'd recommend asking the plugin author too.
