### ISSUE TITLE
VFX Particles not emitting much particles in High End Laptop.

### ISSUE THREAD

**Issue by Hiran-Nair** [keijiro/Smrvfx#36]
I tried bodytracking in this VFX and when I move my hands, I am not able to see the particles coming out of it. In my Low-Spec Laptop, it is working very fine without any problem but when I tried to run this on a High End Laptop, I move my hands very hard and I only see very few particles that is emitting. The Line Effect VFX is working properly it's only the Particles one. Could you please tell me how to solve this.
**P.S**: Attaching here is a short video for your reference for this problem

https://user-images.githubusercontent.com/105865232/188083953-1eea83c9-eedd-4473-b342-25fd1daa08d1.mp4

**Comment by keijiro** [comment]
Did you enable vsync?

**Comment by Hiran-Nair** [comment]
> Did you enable vsync?

No I guess...cause on the low end laptop it was working fine and I don't know where that option is

**Comment by keijiro** [comment]
Could you try enabling it? Too much high FPS wastes the particle budget. I'd recommend using Google to find it (better than my broken English explanation).

**Comment by Hiran-Nair** [comment]
> Could you try enabling it? Too much high FPS wastes the particle budget. I'd recommend using Google to find it (better than my broken English explanation).

Okay thanks. Now it's working much properly. I enabled the V-Sync in the Play Mode and now it works

**Comment by keijiro** [comment]
I'm closing this issue now as "resolved".
