### ISSUE TITLE
How to make it works without optimize new character's fbx？

### ISSUE THREAD

**Issue by LeeLexHong** [keijiro/Smrvfx#38]
When I try to create a new character with this VFX Graph to emit particles，it looks work very well.
 But sometimes it do not match character.
![Gif](https://user-images.githubusercontent.com/26814549/191712837-ee42dfee-f4c7-490a-b0fe-cec87794ebee.gif)
I used this free character   [https://assetstore.unity.com/packages/3d/characters/humanoids/sci-fi/futuristic-soldier-scifi-character-202085](url).
it work very well after i optimize game object in new character's fbx .
I need character's bones because I'm doing Body Pose Tracker.

**Comment by keijiro** [comment]
I guess you're giving a wrong transform as the Source Transform. Please try setting several different transforms to get a correct one.

**Comment by keijiro** [comment]
I'm closing this issue now as answered. Please reopen it if it still reproduces.

**Comment by LeeLexHong** [comment]
Maybe I expressed it something the matter.
How to make it works perfectly when fbx file`s not check “Optimize Game Objects” like this 
![无优化](https://user-images.githubusercontent.com/26814549/194791892-ed5a5fcd-dfac-4aea-a734-9c2c4a05aa4f.png)

**Comment by keijiro** [comment]
This issue doesn't reproduced on my side: I replaced "Beta Optimized" to "Beta", and it worked correctly.
