### ISSUE TITLE
the namespace "RaycastHit2D"

### ISSUE THREAD

**Issue by Levrden** [keijiro/Smrvfx#5]
Hi,
I would like to try you project, but when I launch it, I have these four errors : 

> C:\Program Files\Unity\Hub\Editor\2019.2.0b4\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\EventSystem\Raycasters\Physics2DRaycaster.cs(16,9): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

> C:\Program Files\Unity\Hub\Editor\2019.2.0b4\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\Utility\ReflectionMethodsCache.cs(10,25): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

> C:\Program Files\Unity\Hub\Editor\2019.2.0b4\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\Utility\ReflectionMethodsCache.cs(12,25): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

> C:\Program Files\Unity\Hub\Editor\2019.2.0b4\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\Utility\ReflectionMethodsCache.cs(13,74): error CS0246: The type or namespace name 'RaycastHit2D' could not be found (are you missing a using directive or an assembly reference?)

I have tried installing the textmeshpro package, and the postprocessing one, updated everyinstalled packages, and still the same :(

Do you have an idea to resolve the problem ?

**Comment by Levrden** [comment]
Okay... it looks like it's now okay, i had to go to package manager/ built-in packages and enable physics2D

**Comment by TheXRGuy** [comment]
I had the exact same problem. This solved it! Big Question: Why is it disabled in the first place???
