### ISSUE TITLE
Package to use in another project ?

### ISSUE THREAD

**Issue by Levrden** [keijiro/Smrvfx#6]
Hello,
I have finally achieved to make it work, and it's great !
I want to use it for a vr project for the leap motion hands, in a lwrp, so i used your lwrp branch 
But after i have ducplicated everything, i can't make it work on another project.
i used ethan for testing prupose and here is what i have
![image](https://user-images.githubusercontent.com/24231978/61961069-152af400-afc7-11e9-9e3f-0c36a8e73512.png)
Do you have any idea to help me ?
Thanks

**Comment by keijiro** [comment]
Could you share the project?

**Comment by Levrden** [comment]
Well i feel stupid, i have tried anothertime to send you an empty project and i have understood that i forgot to update the rendered textures in the graph...
But i have another issue :D i will check again and maybe open another thread
Thank you again for your reactivity !
