### ISSUE TITLE
LWRP-Line Effect

### ISSUE THREAD

**Issue by Levrden** [keijiro/Smrvfx#7]
Hi
I love the Line effect on the HDRP project, but my project is on LWRP
I tried to duplicate it on the LWRP 2019.2.0b4, but it doesn't work
Here is the project
https://send.firefox.com/download/0202fbe926de4ef8/#AtnxJDDM9lElONPBEd_xeA

Thanks

**Comment by keijiro** [comment]
It seems you corrupted Lines.vfx. I'd recommend starting over again. Or try this: [Lines.vfx.zip](https://github.com/keijiro/Smrvfx/files/3444885/Lines.vfx.zip)

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if the issue still reproduces.
