### ISSUE TITLE
On playback Karate in editor, see the particle stream but no avatar

### ISSUE THREAD

**Issue by jBachalo** [keijiro/Smrvfx#8]
Ok so first resolved error about missing namespace 'RaycastHit2D" by enabling Physics2D in PackageManager

But when I play back Karate scene I can see the particle stream but no avatar
Using 2019.2 on mac OS Mojave.

I also see a pink shader when I select the Avatar Body prefab in my Project (see attached)

Troubleshooting suggestions?

I also installed this git extension by copying the Editor folder to my Assets folder
UpmGitExtension

![Screen Shot 2019-08-14 at 3 06 55 PM](https://user-images.githubusercontent.com/247784/63048993-b1009f00-bea5-11e9-904b-d5e3544355b5.png)
![Screen Shot 2019-08-14 at 3 11 04 PM](https://user-images.githubusercontent.com/247784/63049022-c2e24200-bea5-11e9-9d22-03f595531205.png)

**Comment by keijiro** [comment]
Could you start over using Unity 2019.1?

**Comment by jBachalo** [comment]
That was it. Thanks!
